-- 코드를 작성해주세요
# SELECT a.ID, a.GENOTYPE, b.ID PARENT_GENOTYPE
# FROM ECOLI_DATA a
# JOIN ECOLI_DATA b ON a.PARENT_ID = b.ID
# # WHERE a.GENOTYPE & b.ID = b.ID
# ORDER BY a.ID ASC;

SELECT a.ID, a.GENOTYPE, b.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA a
JOIN ECOLI_DATA b ON a.PARENT_ID = b.ID
WHERE a.GENOTYPE & b.GENOTYPE = b.GENOTYPE
ORDER BY a.ID ASC;